Web/FimpleWeb/Home/Models/Entity/Comentario.cs
using System;

namespace Home.Models.Entity
{
    public class Comentario
    {
        public int Id { get; set; }
        public string Conteudo { get; set; }
        public Usuario Usuario { get; set; }
        public Publicacao Publicacao { get; set; }
        public Evento Evento { get; set; }

        public DateTime updatedAt { get; set; }
    }
}

Web/FimpleWeb/Home/Models/Entity/Evento.cs
using System;
using System.Collections.Generic;

namespace Home.Models.Entity
{
    public class Evento
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Conteudo { get; set; }
        public string Local { get; set; }
        public DateTime Data { get; set; }
        public Usuario Usuario { get; set; }
        public Entidade Entidade { get; set; }
        public Categoria Categoria { get; set; }
        public Curso Curso { get; set; }
        public IEnumerable<Usuario> Participantes { get; set; }
        public IEnumerable<Comentario> Comentarios { get; set; }
    }
}

Web/FimpleWeb/Home/Controllers/Evento/EventoController.cs
using Home.Application.Evento;
using Home.Application.Timeline;
using Home.Infra;
using Home.Models.Entity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Home.Controllers.Evento
{
    public class EventoController : BaseController
    {
        private readonly IEventoApp _eventoApp;
        private readonly IComentarioEventoApp _comentarioApp;

        public EventoController(IEventoApp eventoApp, IComentarioEventoApp comentarioApp)
        {
            _eventoApp = eventoApp;
            _comentarioApp = comentarioApp;
        }

        public ActionResult Index()
        {
            try
            {
                ViewBag.NomeUsuario = UsuarioLogado.Nome;
                return View(UsuarioLogado);
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        public ActionResult GetAll(int pagina)
        {
            try
            {
                var response = _eventoApp.GetAll(UsuarioLogado.Id, pagina);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                var eventos = JsonConvert.DeserializeObject<IEnumerable<Models.Entity.Evento>>(response.Content.ReadAsStringAsync().Result);
                ViewBag.UsuarioLogado = UsuarioLogado;
                return View("_Evento", eventos);
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        public ActionResult Post(Models.Entity.Evento evento)
        {
            try
            {
                var response = _eventoApp.Post(evento);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        public ActionResult Put(Models.Entity.Evento evento)
        {
            try
            {
                var response = _eventoApp.Put(evento);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                var response = _eventoApp.Delete(id);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        [ValidateInput(false)]
        public ActionResult PostComentario(Comentario comentario)
        {
            try
            {
                var response = _comentarioApp.Post(comentario);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        [ValidateInput(false)]
        public ActionResult PutComentario(Comentario comentario)
        {
            try
            {
                var response = _comentarioApp.Put(comentario);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        public ActionResult DeleteComentario(int id)
        {
            try
            {
                var response = _comentarioApp.Delete(id);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }
    }
}

Web/FimpleWeb/Home/Controllers/Eventos/EventosController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Home.Application.Eventos;
using Home.Application.Timeline;
using Home.Infra;
using Home.Models.Entity;
using Newtonsoft.Json;

namespace Home.Controllers.Eventos
{
    public class EventosController : BaseController
    {
        private readonly IEventoApp _eventoApp;
        private readonly IComentarioApp _comentarioApp;

        public EventosController(IEventoApp eventoApp, IComentarioApp comentarioApp)
        {
            _eventoApp = eventoApp;
            _comentarioApp = comentarioApp;
        }

        public ActionResult Index()
        {
            try
            {
                ViewBag.NomeUsuario = UsuarioLogado.Nome;
                return View(UsuarioLogado);
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        public ActionResult GetAll(int pagina)
        {
            try
            {
                var response = _eventoApp.GetAll(UsuarioLogado.Id, pagina);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                var eventos = JsonConvert.DeserializeObject<IEnumerable<Evento>>(response.Content.ReadAsStringAsync().Result);
                ViewBag.UsuarioLogado = UsuarioLogado;
                return View("_Evento", eventos);
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        public ActionResult Post(Evento evento)
        {
            try
            {
                var response = _eventoApp.Post(evento);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        public ActionResult Put(Evento evento)
        {
            try
            {
                var response = _eventoApp.Put(evento);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                var response = _eventoApp.Delete(id);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        [ValidateInput(false)]
        public ActionResult PostComentario(Comentario comentario)
        {
            try
            {
                var response = _comentarioApp.Post(comentario);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        [ValidateInput(false)]
        public ActionResult PutComentario(Comentario comentario)
        {
            try
            {
                var response = _comentarioApp.Put(comentario);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        public ActionResult DeleteComentario(int id)
        {
            try
            {
                var response = _comentarioApp.Delete(id);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }
    }
}

Web/FimpleWeb/Home/Controllers/TimeLine/TimeLineController.cs
using Home.Application.Timeline;
using Home.Infra;
using Home.Models.Entity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Home.Controllers.Timeline
{
    public class TimelineController : BaseController
    {
        private readonly IPublicacaoApp _publicacaoApp;
        private readonly IComentarioApp _comentarioApp;

        public TimelineController(IPublicacaoApp publicacaoApp, IComentarioApp comentarioApp)
        {
            _publicacaoApp = publicacaoApp;
            _comentarioApp = comentarioApp;
        }

        public ActionResult Index()
        {
            try
            {
                ViewBag.NomeUsuario = UsuarioLogado.Nome;
                return View(UsuarioLogado);
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        public ActionResult GetAll(int pagina)
        {
            try
            {
                var response = _publicacaoApp.GetAll(UsuarioLogado.Id, pagina);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                var publicacoes = JsonConvert.DeserializeObject<IEnumerable<Publicacao>>(response.Content.ReadAsStringAsync().Result);
                ViewBag.UsuarioLogado = UsuarioLogado;
                return View("_Publicacao", publicacoes);
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        public ActionResult Post(Publicacao publicacao)
        {
            try
            {
                var response = _publicacaoApp.Post(publicacao);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        public ActionResult Put(Publicacao publicacao)
        {
            try
            {
                var response = _publicacaoApp.Put(publicacao);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                var response = _publicacaoApp.Delete(id);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        [ValidateInput(false)]
        public ActionResult PostComentario(Comentario comentario)
        {
            try
            {
                var response = _comentarioApp.Post(comentario);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        [ValidateInput(false)]
        public ActionResult PutComentario(Comentario comentario)
        {
            try
            {
                var response = _comentarioApp.Put(comentario);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        public ActionResult DeleteComentario(int id)
        {
            try
            {
                var response = _comentarioApp.Delete(id);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }
    }
}

Web/FimpleWeb/Home/Views/Eventos/Index.cshtml
@model Home.Models.Entity.Usuario
<!-- BEGIN PAGE HEADER-->
<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.css" rel="stylesheet">
<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.js"></script>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-users"></i>
            <a href="@Url.Action("Index", "Eventos")">Eventos</a>
        </li>
    </ul>
    <div class="page-toolbar">  
        <div class="btn-group">
            <button type="button" class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" onclick="addPost()">
                Novo Evento
            </button>
        </div>
    </div>
</div>
<!-- BEGIN PAGE CONTENT-->
<div class="timeline">
    <!-- TIMELINE ITEM -->
    <!-- BEGIN NOVA POSTAGEM -->
    <div class="timeline-item" id="novaPostagem" style="display: none">
        <div class="timeline-badge">
            <img class="timeline-badge-userpic" src="~/assets/img/placeholder.jpg">
        </div>
        <div class="timeline-body">
            <div class="timeline-body-arrow">
            </div>
            <div class="timeline-body-head">
                <div class="timeline-body-head-caption">
                    <a href="javascript:;" class="timeline-body-title font-blue-madison">@Model.NomeCompleto</a>
                </div>
                <div class="timeline-body-head-actions">
                    <div class="btn-group btn-salvar">
                        <button class="btn btn-circle green-haze btn-sm" id="btnSalvarPublicacao" type="button" data-toggle="dropdown" data-close-others="true">
                            Salvar <i class="fa fa-floppy-o "></i>
                        </button>
                    </div>
                </div>
            </div>
            <div class="timeline-body-content">
                <div id="novoPost">
                </div>
            </div>
        </div>
    </div>
    <!-- END NOVA POSTAGEM -->
    <!-- BEGIN PUBLICAÇÕES -->
    <div class="timeline-item" id="divPublicacoes"></div>
    <!-- END PUBLICAÇÕES -->
    <!-- END TIMELINE ITEM -->
</div>
<!-- END PAGE CONTENT-->

<script>
    $("#MenuLateral li.start.active.open").removeClass("start active open");
    $("#liEventos").addClass("start active open");
    $("#liEventos").find("span:not(:first)").addClass("selected");

    $("#novoPost").summernote({
        toolbar: false,
        height: 200,
        minHeight: 200,
        maxHeight: 500
    });

   function addPost() {
        $("#novaPostagem").show();
        $("#novoPost").summernote("focus");
    }

    function editarPost(id, element) {
        $("[data-post="+ id + "]").summernote({
            toolbar: false,
            height: 200,
            minHeight: 200,
            maxHeight: 500
        });
        $(element).closest(".timeline-body-head-actions").find(".btn-salvar").show();
    }

    function addComentario(obj) {
        $(obj).closest("[data-add-coment]").hide().next("[data-salvar-coment]").show();
        $(obj).closest(".col-md-12.blog-page").find("[data-row-coment]").show();
    }

</script>
<script>

    var buscarPublicacoes = (function publicacao(callback, isUpdate) {
        $.get('@Url.Action("GetAll", "Timeline")', {
            pagina: Math.ceil($(".timeline-body").length / 30)
        })
        .done((data) => {
            isUpdate
            ? $("#divPublicacoes").prepend(data)
            : $("#divPublicacoes").html(data);

            if (typeof callback == "function")
                callback();
        })
        .fail((xhr) => {
            $("#divPublicacoes").html("<h1>Erro ao buscar publicações</h1>");
        });

        return publicacao;
    })();

    $("#btnSalvarPublicacao").click(() => {
        $.post('@Url.Action("Post", "Timeline")',
            {
                Titulo: "Título padrão",
                Conteudo: $(".note-editable.panel-body:first").text().trim(),
                Data: new Date(),
                Usuario: { Id: '@Model.Id' },
                Entidade: { Id: 1 },
                Categoria: { Id: 0 },
                Curso: { Id: 0 }
            })
            .done(() => {
                $("#novaPostagem").hide();
                $(".note-editable.panel-body").text("");
                $('.divPost').summernote("destroy");
                buscarPublicacoes();
            })
            .fail(() => {
                $("#divPublicacoes").html("<h1>Erro ao salvar publicação</h1>");
            });
    });

    function salvarEdicao(id, obj) {
        $.post('@Url.Action("Put", "Timeline")',
           {
               Id: id,
               Titulo: "Título padrão",
               Conteudo: $("[data-post=" + id + "]").closest(".timeline-body-content").find(".note-editable.panel-body:first").text().trim(),
               Data: new Date(),
               Usuario: { Id: '@Model.Id' },
               Entidade: { Id: 1 },
               Categoria: { Id: 0 },
               Curso: { Id: 0 }
           })
           .done(() => {
               $(".note-editable.panel-body").text("");
               $('.divPost').summernote("destroy");
               buscarPublicacoes(() => {
                   $(obj).closest(".timeline-badge").remove();
                   $(obj).closest(".timeline-body").remove();
               });
           })
           .fail(() => {
               $("#divPublicacoes").html("<h1>Erro ao salvar publicação</h1>");
           });
    }

    function excluirPublicacao(id) {
        $.get('@Url.Action("Delete", "Timeline")',
            {
                id: id
            })
            .fail(() => {
                $("#divPublicacoes").html("<h1>Erro ao excluir publicação</h1>");
            });
    }

    function salvarComentario(obj) {
        $.post('@Url.Action("PostComentario", "Timeline")',
            {
                Publicacao: { Id: $(obj).closest("[data-id-publicacao]").attr("data-id-publicacao") },
                Conteudo: $(obj).closest(".col-md-12.blog-page").find(".note-editable p").text(),
                Usuario: { Id: '@Model.Id' }
            })
            .done(() => {
                $("#novaPostagem").hide();
                $("textarea.note-codable").val("");
                $('.divPost').summernote("destroy");
                buscarPublicacoes();
            })
            .fail(() => {
                $("#divPublicacoes").html("<h1>Erro ao salvar comentário</h1>");
            })
            .complete(() => {
                $(obj).closest("[data-add-coment]").show().next("[data-salvar-coment]").hide();
                $(obj).closest(".col-md-12 blog-page").find("[data-div-coment]").summernote("destroy");
            });
    }

    function excluirComentario(id) {
        $.get('@Url.Action("DeleteComentario", "Timeline")',
            {
                id: id
            })
            .fail(() => {
                $("#divPublicacoes").html("<h1>Erro ao excluir comentário</h1>");
            });
    }

    function abrirchat(idUsuario) {
        $('body').toggleClass('page-quick-sidebar-open');
        $(".media[data-user-id=" + idUsuario + "]").trigger("click");
    }

</script>

Web/FimpleWeb/Home/Views/Eventos/_Comentarios.cshtml
@model Home.Models.Entity.Evento
@{ Layout = null;}

<!-- COMENTARIOS -->
<div class="row" data-id-publicacao="@Model.Id">
    <div class="col-md-12 blog-page">
        <h3>Comentarios</h3>
        @if (Model.Comentarios != null && Model.Comentarios.Any())
        {
            foreach (var comentario in Model.Comentarios)
            {
                <div class="row">
                    <div class="col-md-9 article-block">
                        <div class="media">
                            <a href="javascript:;" class="pull-left">
                                <img alt="" src="~/assets/img/placeholder.jpg" class="media-object">
                            </a>
                            <div class="media-body">
                                <h4 class="media-heading font-grey-cascade">
                                    <a href="javascript:;">@comentario.Usuario.NomeCompleto</a>
                                    <i>Há algum tempo</i>
                                    <a href="javascript:;" class="btn btn-xs black">
                                        <span class="md-click-circle md-click-animate" style="height: 65px; width: 65px; top: -22.5px; left: 2.07813px;"></span>
                                        <i class="fa fa-comments-o"></i>
                                    </a>
                                </h4>
                                <div>
                                    @comentario.Conteudo
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr />
                </div>
            }
        }
        <div class="row" data-row-coment style="display: none">
            <div class="col-md-9 article-block">
                <div class="media">
                    <a href="javascript:;" class="pull-left">
                        <img alt="" src="~/assets/img/placeholder.jpg" class="media-object">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading font-grey-cascade">
                            <a href="javascript:;">@ViewBag.UsuarioLogado.Nome</a>
                            <i></i>
                        </h4>
                        <div data-div-coment></div>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <div class="btn-group" data-add-coment>
                <button class="btn btn-circle green-haze btn-sm" type="button" data-toggle="dropdown" data-close-others="true" onclick="addComentario(this)">
                    Comentar <i class="fa fa-comment-o"></i>
                </button>
            </div>
            <div class="btn-group" style="display: none" data-salvar-coment>
                <button class="btn btn-circle green-haze btn-sm" type="button" data-toggle="dropdown" data-close-others="true" onclick="salvarComentario(this)">
                    Salvar <i class="fa fa fa-floppy-o"></i>
                </button>
            </div>
        </div>
    </div>
</div>
<!-- FIM COMENTARIOS -->

<script>
    
    $("[data-div-coment]")
       .summernote({
           toolbar: false,
           height: 50,
           minHeight: 50,
           maxHeight: 100
       });

</script>

Web/FimpleWeb/Home/Views/Eventos/_Evento.cshtml
@model IEnumerable<Home.Models.Entity.Evento>
@{ Layout = null;}

@if (Model != null && Model.Any())
{
    foreach (var evento in Model)
    {
        <div class="timeline-badge">
            <img class="timeline-badge-userpic" src="~/assets/img/placeholder.jpg">
        </div>
        <div class="timeline-body">
            <div class="timeline-body-arrow">
            </div>
            <div class="timeline-body-head">
                <div class="timeline-body-head-caption">
                    <a href="javascript:;" class="timeline-body-title font-blue-madison">@evento.Usuario.NomeCompleto</a>

                    <span class="timeline-body-time font-grey-cascade">Há algum tempo</span>
                    @if (evento.Usuario.Id != ViewBag.UsuarioLogado.Id)
                    {
                        <a href="javascript:;" onclick="abrirChat('@evento.Usuario.Id')" class="btn btn-xs black">
                            <span class="md-click-circle md-click-animate" style="height: 65px; width: 65px; top: -22.5px; left: 2.07813px;"></span>
                            <i class="fa fa-comments-o"></i>
                        </a>
                    }
                </div>
                <div class="timeline-body-head-actions">
                    @if (evento.Usuario.Id == ViewBag.UsuarioLogado.Id)
                    {
                        <div class="btn-group">
                            <button class="btn btn-circle green-haze btn-sm dropdown-toggle" type="button" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                Ações <i class="fa fa-angle-down"></i>
                            </button>
                            <ul class="dropdown-menu pull-right" role="menu">
                                <li><a href="javascript:;" onclick="editarPost('@evento.Id', this)">Editar </a></li>

                                <li class="divider">
                                </li>
                                <li><a href="@Url.Action("Index", "Timeline")" onclick="excluirPublicacao('@evento.Id')">Excluir </a></li>
                            </ul>
                        </div>
                    }
                    <div class="btn-group btn-salvar" style="display: none">
                        <button class="btn btn-circle green-haze btn-sm" onclick="salvarEdicao('@evento.Id', this)" type="button" data-toggle="dropdown" data-close-others="true">
                            Salvar <i class="fa fa-floppy-o "></i>
                        </button>
                    </div>
                </div>
            </div>
            <div class="timeline-body-content">
                <div class="divPost" data-post="@evento.Id">
                    @evento.Conteudo
                </div>
            </div>
            <br>
            <hr>
            @Html.Partial("_Comentarios", evento)
        </div>
    }
    <script> if ($("[data-nocontent]").length) $("[data-nocontent]").remove();</script>
}
else
{
    <div class="timeline-body" data-nocontent>
        <div class="timeline-body-content">
            <div class="divPost">
                Nenhum evento encontrado até o momento. Aproveite e faça você o primeiro :)
            </div>
        </div>
        <br>
        <hr>
    </div>
}