Web/FimpleWeb/Home/Controllers/Chat/ChatController.cs
using Home.Application.Chat;
using Home.Infra;
using Home.Models.Dto;
using Home.Models.Entity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Home.Controllers.Chat
{
    public class ChatController : BaseController
    {
        private readonly IChatApp _chatApp;

        public ChatController(IChatApp chatApp)
        {
            _chatApp = chatApp;
        }

        public ActionResult Index()
        {
            try
            {
                // Fazendo requisição para buscar conversas do usuário
                var response = _chatApp.GetConversas(UsuarioLogado.Id);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                // Instanciando Chat e deserializando resposta
                var conversas = JsonConvert.DeserializeObject<IEnumerable<Mensagem>>(response.Content.ReadAsStringAsync().Result);
                var chat = new ChatDto(UsuarioLogado, conversas);

                return View(chat);
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        public ActionResult BuscarMensagens(int idUsuarioEnvio, int idUsuarioDestino, int pagina)
        {
            try
            {
                // Fazendo requisição para buscar mensagens do usuário
                var response = _chatApp.Get(idUsuarioEnvio, idUsuarioDestino, pagina);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                // Instanciando Mensagens e deserializando resposta
                var chat = new ChatDto
                {
                    Conversas = (IEnumerable<Mensagem>) JsonConvert.DeserializeObject<IEnumerable<Mensagem>>(response.Content.ReadAsStringAsync().Result)
                        .OrderBy(x => x.DataEnvio) ?? new List<Mensagem>()
                };

                return Json(chat, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }
    }
}

Web/FimpleWeb/Home/Controllers/Evento/EventoController.cs
using Home.Application.Evento;
using Home.Application.Timeline;
using Home.Infra;
using Home.Models.Entity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Home.Controllers.Evento
{
    public class EventoController : BaseController
    {
        private readonly IEventoApp _eventoApp;
        private readonly IComentarioEventoApp _comentarioApp;

        public EventoController(IEventoApp eventoApp, IComentarioEventoApp comentarioApp)
        {
            _eventoApp = eventoApp;
            _comentarioApp = comentarioApp;
        }

        public ActionResult Index()
        {
            try
            {
                ViewBag.NomeUsuario = UsuarioLogado.Nome;
                return View(UsuarioLogado);
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        public ActionResult GetAll(int pagina)
        {
            try
            {
                var response = _eventoApp.GetAll(UsuarioLogado.Id, pagina);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                var eventos = JsonConvert.DeserializeObject<IEnumerable<Models.Entity.Evento>>(response.Content.ReadAsStringAsync().Result);
                ViewBag.UsuarioLogado = UsuarioLogado;
                return View("_Evento", eventos);
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        public ActionResult Post(Models.Entity.Evento evento)
        {
            try
            {
                var response = _eventoApp.Post(evento);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        public ActionResult Put(Models.Entity.Evento evento)
        {
            try
            {
                var response = _eventoApp.Put(evento);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                var response = _eventoApp.Delete(id);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        [ValidateInput(false)]
        public ActionResult PostComentario(Comentario comentario)
        {
            try
            {
                var response = _comentarioApp.Post(comentario);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        [ValidateInput(false)]
        public ActionResult PutComentario(Comentario comentario)
        {
            try
            {
                var response = _comentarioApp.Put(comentario);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        public ActionResult DeleteComentario(int id)
        {
            try
            {
                var response = _comentarioApp.Delete(id);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                return new EmptyResult();
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }
    }
}

Web/FimpleWeb/Home/Controllers/Mapa/MapaController.cs
using Home.Infra;
using System.Web.Mvc;

namespace Home.Controllers.Mapa
{
    public class MapaController : BaseController
    {
        public ActionResult Index()
        {
            ViewBag.NomeUsuario = UsuarioLogado.Nome;
            return View(UsuarioLogado);
        }
    }
}

Web/FimpleWeb/Home/Controllers/Perfil/PerfilController.cs
using Home.Application.Usuario;
using Home.Infra;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Home.Controllers.Perfil
{
    public class PerfilController : BaseController
    {
        private readonly IUsuarioApp _usuarioApp;

        public PerfilController(IUsuarioApp usuarioApp)
        {
            _usuarioApp = usuarioApp;
        }

        [Route("Perfil/{idUsuario}")]
        [Route("Perfil/")]
        [HttpGet]
        public ActionResult Index(int? idUsuario)
        {
            try
            {
                ViewBag.NomeUsuario = UsuarioLogado.Nome;
                ViewBag.IsUsuarioLogado = !idUsuario.HasValue || idUsuario == UsuarioLogado.Id;

                if (!idUsuario.HasValue || idUsuario == UsuarioLogado.Id)
                    return View("Index", UsuarioLogado);

                var response = _usuarioApp.Get((int)idUsuario);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage(response.Content.ReadAsStringAsync().Result);

                var usuario = JsonConvert.DeserializeObject<Models.Entity.Usuario>(response.Content.ReadAsStringAsync().Result);
                return View("Index", usuario);
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        #region --> Abas <--
        [Route("Perfil/GetInfo/")]
        [HttpGet]
        public ActionResult GetInfo(int? idUsuario)
        {
            try
            {
                var retorno = _usuarioApp.Get(idUsuario ?? UsuarioLogado.Id);
                if (!retorno.IsSuccessStatusCode)
                    return ErrorMessage(retorno.Content.ReadAsStringAsync().Result);

                var usuario = JsonConvert.DeserializeObject<Models.Entity.Usuario>(
                    retorno.Content.ReadAsStringAsync().Result);

                ViewBag.IsUsuarioLogado = !idUsuario.HasValue || idUsuario == UsuarioLogado.Id;
                return View("Abas/_InformacaoPessoal", usuario);
            }
            catch (Exception ex)
            {
                return ErrorMessage(ex.Message);
            }
        }

        [Route("Perfil/GetMudarAvatar/")]
        [HttpGet]
        public ActionResult GetMudarAvatar()
        {
            return PartialView("Abas/_MudarAvatar");
        }

        [Route("Perfil/GetMudarSenha/")]
        [HttpGet]
        public ActionResult GetMudarSenha()
        {
            return PartialView("Abas/_MudarSenha", UsuarioLogado);
        }

        [Route("Perfil/GetUsuarioBloqueado/")]
        [HttpGet]
        public ActionResult GetUsuarioBloqueado()
        {
            var retorno = _usuarioApp.GetUsuarioBloqueado(UsuarioLogado.Id);
            if (!retorno.IsSuccessStatusCode)
                return ErrorMessage(retorno.Content.ReadAsStringAsync().Result);

            var usuario = JsonConvert.DeserializeObject<IEnumerable<Models.Entity.Usuario>>(
                retorno.Content.ReadAsStringAsync().Result);

            return PartialView("Abas/_UsuarioBloqueado", usuario);

        }
        #endregion
    }
}

Web/FimpleWeb/Home/Views/Shared/_Layout.cshtml
@model Home.Models.Entity.Usuario
<!DOCTYPE html>

<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <title>Fimple</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" href="~/assets/icon/favicon.ico" />

    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.3.2/css/simple-line-icons.css" rel="stylesheet" type="text/css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css" rel="stylesheet" type="text/css" />

    @Styles.Render("~/assets/css/externos")
    @Styles.Render("~/assets/css")
    @Scripts.Render("~/assets/js/jQuery")
    @Scripts.Render("~/assets/js/externos")
    @Scripts.Render("~/assets/js")

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/locales/bootstrap-datepicker.pt-BR.min.js" type="text/javascript"></script>

</head>
<body class="page-md page-header-fixed page-quick-sidebar-over-content page-container-bg-solid">
    <div id="divErrorLayout">@Html.ValidationSummary()</div>
    <div class="page-header md-shadow-z-1-i navbar navbar-fixed-top">
        <div class="page-header-inner">
            <div class="page-logo">
                <a href="@Url.Action("Index", "Timeline")">
                    <img src="~/assets/img/logo-big.png" alt="logo" class="logo-default" />
                </a>
                <div class="menu-toggler sidebar-toggler hide"></div>
            </div>
            <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
            </a>
            <div class="top-menu">
                <ul class="nav navbar-nav pull-right">
                    @Html.Action("Index", "Notificacao")

                    <li class="dropdown dropdown-user">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                            <img alt="" class="img-circle" src="~/assets/img/placeholder.jpg" />
                            <span class="username username-hide-on-mobile">@ViewBag.NomeUsuario</span>
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-default">
                            <li>
                                <a href="@Url.Action("Index", "Perfil")"><i class="icon-user"></i> Meu Perfil</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Sair", "Login")"><i class="icon-key"></i> Sair</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown dropdown-quick-sidebar-toggler">
                        <a href="javascript:;" class="dropdown-toggle">
                            <span class="badge badge-default"></span>
                            <i class="fa fa-comments-o"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="page-container">
        <div class="page-sidebar-wrapper">
            <div class="page-sidebar navbar-collapse collapse" id="MenuLateral">
                <ul class="page-sidebar-menu page-sidebar-menu-light " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
                    <li class="sidebar-toggler-wrapper">
                        <div class="sidebar-toggler"></div>
                    </li>
                    <li class="start active open" id="liTimeline">
                        <a href="@Url.Action("Index", "Timeline")">
                            <i class="icon-home"></i>
                            <span class="title">Timeline</span>
                            <span class="selected"></span>
                        </a>
                    </li>
                    <li class="" id="liEventos">
                        <a href="@Url.Action("Index", "Evento")">
                            <i class="fa fa-users"></i>
                            <span class="title">Eventos</span>
                            <span class=""></span>
                        </a>
                    </li>
                    <li class="" id="liMapa">
                        <a href="@Url.Action("Index", "Mapa")">
                            <i class="fa fa-map"></i>
                            <span class="title">Mapa</span>
                            <span class=""></span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <div>@Html.ValidationSummary()</div>
        <div class="page-content-wrapper">
            <div class="page-content">
                <div id="divContent">@RenderBody()</div>

                <a href="javascript:;" class="page-quick-sidebar-toggler"><i class="icon-close"></i></a>
                @Html.Action("Index", "Chat")
            </div>
        </div>
    </div>

    <div class="page-footer">
        <div class="page-footer-inner">
            2017 © Fimple
        </div>
    </div>
    <script>

        $(document).ready(function () {
            Metronic.init();
            Layout.init();
            QuickSidebar.init();

        });

        function putNotificacao(notificacao) {
            $.post('@Url.Action("Put", "Notificacao")',
                {
                    Id: notificacao
                })
                .done(() => {
                    $("[data-count-notification]").text(!+$("[data-count-notification]:first").text() ? 0 : (+$("[data-count-notification]:first").text() - 1));
                })
                .fail((xhr) => {
                    notify.error(xhr.responseText);
                });
        }

    </script>
</body>

</html>

Web/FimpleWeb/Home/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>

<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <title>Fimple</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" href="~/assets/icon/favicon.ico" />

    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.3.2/css/simple-line-icons.css" rel="stylesheet" type="text/css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css" rel="stylesheet" type="text/css" />
    
    @Styles.Render("~/assets/css/externos")
    @Styles.Render("~/assets/css")
    @Scripts.Render("~/assets/js/jQuery")
    @Scripts.Render("~/assets/js/externos")
    @Scripts.Render("~/assets/js")

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/locales/bootstrap-datepicker.pt-BR.min.js" type="text/javascript"></script>

</head>
<body>
    <div class="page-md login">
        <div class="logo">
            <a href="#"><img src="~/assets/img/logo-big.png" alt=""/></a>
        </div>
        <div id="divContent" class="content">@RenderBody()</div>
        <div class="copyright">2017 © Fimple.</div>
    </div>
</body>
</html>